databases:
  - name: book-appointment
    databaseName: book_appointment
    user: book_appointment_user

services:
  - type: web
    name: book-appointment
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: book_appointment
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false